In [14]:
import numpy as np

In [24]:
# Question 1
a = np.array([[7], [8], [9]])
b = np.array([[9], [10], [11]])
np.hstack((a,b))

array([[ 7,  9],
       [ 8, 10],
       [ 9, 11]])

In [29]:
# Question 1
a = np.array([8, 9, 10])
b = np.array([9, 10, 11])
np.vstack((a,b))

array([[ 8,  9, 10],
       [ 9, 10, 11]])

In [30]:
# Question 2
np.intersect1d = 

array([ 9, 10])

In [45]:
# Question 3
newa = np.where(np.logical_and(a > 5, a < 10), a, 0)
for i in range(len(newa)):
    if newa[i] != 0:
        print(newa[i])

8
9


In [61]:
# Question 4
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
newiris = np.where(np.logical_and(iris_2d[0] < 5.0, iris_2d[2] > 1.5), iris_2d, 0)
for i in range(len(iris_2d)):
    if iris_2d[i] != 0:
        print(iris_2d[i])

<class 'FileNotFoundError'>: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data not found.

In [60]:
import pandas as pd

In [63]:
# Question 5
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.iloc[0::20,0:2]

<class 'urllib.error.URLError'>: <urlopen error [Errno 23] Host is unreachable>

In [69]:
# Question 6
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df["Min.Price"].fillna(df["Min.Price"].mean(), inplace = True)
df["Max.Price"].fillna(df["Max.Price"].mean(), inplace = True)

<class 'urllib.error.URLError'>: <urlopen error [Errno 23] Host is unreachable>

In [68]:
# Question 7
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
result_sum = df[df.sum(axis = 1) > 100]
print(result_sum)

     0   1   2   3
1   28  15  25  38
5   16  35  18  32
11  23  34  30  32
12  33  25  21  38
13  39  20  24  32
14  22  15  38  36
